apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: import-tests-go-gepmfrii-import
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: import-tests-go-gepmfrii-import 
  name: import-tests-go-gepmfrii-import
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: import-tests-go-gepmfrii-import 
